added login & signup page + api
WildCodeSchool-2024-02/JS-Paris-BrainWaves-P3-Devlog pull request #17
Opened 2024-07-08 14:06 UTC by 0xSxZ

2024-07-08 14:08 UTC, Black-Star-Pen approved these changes
Rien ne me semble problématique .

2024-07-08 14:13 UTC, Brian-boudrioux requested changes
Reste des conflits à gérer (voir commentaire) et tu as supprimer le fichier .env.sample ce qui est interdit !

2024-07-08 14:13 UTC, Brian-boudrioux commented on server/database/schema.sql
>  -- MySQL Workbench Forward Engineering
A lot a conflict here !!!!

2024-07-08 14:14 UTC, Brian-boudrioux commented
> Rien ne me semble problématique .

Mieux regarder la prochaine fois, si je merge tel quel rien ne marche !

2024-07-08 14:27 UTC, Black-Star-Pen commented on server/database/schema.sql
>  -- MySQL Workbench Forward Engineering
Le problème viens du faite qu'il n'a pas mis a jour la database ?

2024-07-09 14:43 UTC, VinchC approved these changes

2024-07-09 14:43 UTC, merged