Header
WildCodeSchool-2024-02/JS-Paris-BrainWaves-P3-Devlog pull request #5
Opened 2024-06-18 13:16 UTC by Erwan60

2024-06-18 13:21 UTC, vingtle approved these changes

2024-06-18 15:34 UTC, VinchC requested changes

2024-06-18 15:34 UTC, VinchC commented on client/src/Router.jsx
> +import Member from "./pages/Member/Menber";
Member/Member

2024-06-18 15:34 UTC, VinchC commented on client/src/components/Header/Header.jsx
> +        <div className="logo-acceuil">
name of the classes in English please

2024-06-18 15:34 UTC, VinchC commented on client/src/components/Header/Header.jsx
> +              <div className="popoverEcrit">
className in English

2024-06-18 15:34 UTC, VinchC commented on client/src/components/Header/Header.jsx
> +                      <img src={profil} alt="profil" className="profil" />
profile

2024-06-18 15:34 UTC, VinchC commented on client/src/components/Header/Header.jsx
> +                    <div className="popoverNom">
className in English

2024-06-18 15:34 UTC, VinchC commented on client/src/components/Header/header.css
> +.profil {
profile

2024-06-18 15:34 UTC, VinchC commented on client/src/components/Header/header.css
> +.logo-acceuil {
English

2024-06-18 15:34 UTC, VinchC commented on client/src/components/Header/header.css
> +.popoverEcrit {
English

2024-06-18 15:34 UTC, VinchC commented on client/src/components/Header/header.css
> +.popoverNom {
English

2024-06-18 15:34 UTC, VinchC commented on client/src/components/Header/header.css
> +.popoverEcrit ul {
English

2024-06-18 15:34 UTC, VinchC commented on client/src/main.jsx
> +import Member from "./pages/Member/Menber";
Member/Member

2024-06-18 15:34 UTC, VinchC commented on client/src/pages/Member/Menber.jsx
> +        <h1>Menber</h1>
Member

2024-06-18 15:34 UTC, VinchC commented on client/src/pages/Member/Menber.jsx
> +function Menber() {
Member

2024-06-18 15:34 UTC, VinchC commented on client/src/pages/Member/Menber.jsx
> +  export default Menber;
Member

2024-06-18 15:34 UTC, VinchC commented on server/database/schema.sql
> +  `Email` VARCHAR(100) NULL,
email

2024-06-18 15:34 UTC, VinchC commented on server/database/schema.sql
> +  `Is_admin` TINYINT NULL,
is_admin NOT NULL default 0

2024-06-18 15:34 UTC, VinchC commented on server/database/schema.sql
> +  `password` VARCHAR(80) NULL,
`password` VARCHAR(255) NOT NULL

2024-06-18 15:34 UTC, VinchC commented on server/database/schema.sql
> +  `username` VARCHAR(50) NULL,
NOT NULL

2024-06-18 15:34 UTC, VinchC commented on server/database/schema.sql
> +  `Email` VARCHAR(100) NULL,
NOT NULL

2024-06-18 15:34 UTC, VinchC commented on server/database/schema.sql
> +  `Team_Name` VARCHAR(55) NULL,
`team_name` NOT NULL

2024-06-18 15:34 UTC, VinchC commented on server/database/schema.sql
> +  `id` INT NOT NULL,
all field names in lower case letter and check nullable property of fields - NOT NULL should be the majority

2024-06-19 08:46 UTC, VinchC approved these changes

2024-06-19 08:46 UTC, merged