footer wip mobile
WildCodeSchool-2024-02/JS-Paris-BrainWaves-P3-Devlog pull request #6
Opened 2024-06-19 12:37 UTC by Black-Star-Pen

2024-06-19 12:41 UTC, vingtle approved these changes

2024-06-19 13:32 UTC, Alexandre78R requested changes

2024-06-19 13:32 UTC, Alexandre78R commented on client/src/components/Footer/Footer.jsx
> +import devlogimage from "../../assets/images/devlog.png";
renamed to camelCase

2024-06-19 13:32 UTC, Alexandre78R commented on client/src/components/Footer/Footer.jsx
> +import instaimage from "../../assets/images/logo.instagram.png";
renamed to camelCase

2024-06-19 13:32 UTC, Alexandre78R commented on client/src/components/Footer/Footer.jsx
> +import linkimage from "../../assets/images/logo.linkedin.png";
renamed to camelCase

2024-06-19 13:32 UTC, Alexandre78R commented on client/src/components/Footer/Footer.jsx
> +import faceimage from "../../assets/images/logo.facebook.png";
renamed to camelCase

2024-06-19 13:32 UTC, Alexandre78R commented on client/src/components/Footer/Footer.jsx
> +    <section id="footer">
Balise html footer

2024-06-19 13:32 UTC, Alexandre78R commented on client/src/components/Footer/footer.css
Next time, use className for CSS instead, and avoid using IDs. For a footer, it's acceptable since you're sure to have only one footer per page, but for other components, it will be rejected.

2024-06-19 13:32 UTC, Alexandre78R commented on client/src/components/Footer/footer.css
> +h2 {
Add classname in to h2

2024-06-19 13:42 UTC, VinchC requested changes

2024-06-19 13:42 UTC, VinchC commented on client/src/components/Footer/footer.css
> +#a-propos,
English

2024-06-19 13:42 UTC, VinchC commented on client/src/components/Footer/footer.css
> +#outil-populaire {
English

2024-06-19 13:42 UTC, VinchC commented on client/src/components/Footer/footer.css
> +.icone-network {
icon-network

2024-06-19 13:42 UTC, VinchC commented on client/src/components/Footer/Footer.jsx
> +        <div className="icone-network">
icon-network

2024-06-19 15:34 UTC, Alexandre78R requested changes

2024-06-19 15:34 UTC, Alexandre78R commented on client/src/components/Footer/Footer.jsx
> +    <section id="footer">
https://developer.mozilla.org/fr/docs/Web/HTML/Element/footer

2024-06-21 12:57 UTC, Alexandre78R requested changes

2024-06-21 12:57 UTC, Alexandre78R commented on client/src/App.jsx
> +    <section>
please change balise in to main 👍

2024-06-21 13:00 UTC, Alexandre78R requested changes

2024-06-21 13:00 UTC, Alexandre78R commented on client/src/components/Footer/footer.css
> +.footer-tilte {
rename title

2024-06-21 13:12 UTC, Alexandre78R approved these changes
Good

2024-06-21 13:12 UTC, merged