Footer
WildCodeSchool-2024-02/JS-Paris-BrainWaves-P3-Devlog pull request #8
Opened 2024-06-26 13:02 UTC by Black-Star-Pen

2024-06-28 14:24 UTC, Erwan60 approved these changes

2024-07-01 07:48 UTC, Alexandre78R requested changes

2024-07-01 07:48 UTC, Alexandre78R commented on client/src/App.css
> +button {
add class name ?

2024-07-01 07:48 UTC, Alexandre78R commented on client/src/components/Collaborater/collaborater.css
> +.Collabo-container {
Rename your css class like the other xxx-xxx without capital letters please

2024-07-01 07:48 UTC, Alexandre78R commented on client/src/components/Footer/Footer.jsx
> +        <div>
div ??  --> fragement react ?

2024-07-01 07:48 UTC, Alexandre78R commented on client/src/components/Collaborater/Collaborater.jsx
> +        <div>
div ??  --> fragement react ? or delete div 👍

2024-07-01 07:48 UTC, Alexandre78R commented on client/src/main.jsx
> +    path: "/Collabo",
collaborator rename please

2024-07-01 07:48 UTC, Alexandre78R commented on client/src/main.jsx
> +    path: "/Collabo",
Place this route in the children of APP

2024-07-01 07:48 UTC, Alexandre78R commented on client/src/main.jsx
> +    path: "/footer",
delete route footer ..

2024-07-01 07:48 UTC, Alexandre78R commented on client/src/pages/Table/Table.jsx
> +    <div>
div ?? --> fragement react ?

2024-07-01 07:48 UTC, Alexandre78R commented on client/src/pages/Welcome/Welcome.jsx
> +      <div className="welcome-page">
replace div ---> main

2024-07-01 13:09 UTC, Alexandre78R approved these changes

2024-07-01 13:09 UTC, merged