Projecthome
WildCodeSchool-2024-02/JS-Paris-BrainWaves-P3-Devlog pull request #9
Opened 2024-06-26 13:42 UTC by Erwan60

2024-06-26 14:12 UTC, Brian-boudrioux requested changes
see the comments above, your feature isnt finish !

2024-06-26 14:12 UTC, Brian-boudrioux commented on client/src/components/Project/project.jsx
> +  const [project, setProject] = useState([
Dont use static data, you should fetch your api in a useEffect and update your state with the data returned by your api

2024-06-26 14:12 UTC, Brian-boudrioux commented on client/src/components/Project/project.jsx
> +    const newProject = prompt("Entrez le nom du nouveau projet :");
prompt ? you need to respect the graphical chart defined in your figma !

2024-06-26 14:12 UTC, Brian-boudrioux commented on server/app/routers/api/router.js
> -const tablesRoutes = require("./tables/router"); // Management des tableaux
Why did you deleted tablesRoutes ? maybe that can affect a other feature of the project, you should not touch any code that in not in concern with your user story

2024-07-01 07:54 UTC, Alexandre78R approved these changes

2024-07-01 07:55 UTC, merged